document.write('<footer class="padding_4x">');
document.write('    <div class="flex">');
document.write('        <section class="flex-content padding_1x">');
document.write('            <div class="footer-logo">');
document.write('                <img src="./frontend/img/logo.jpg" alt="">');
document.write('                <h3 class="mt-2">Nursework</h3>');
document.write('            </div>');
document.write('        </section>');
document.write('        <section class="flex-content padding_1x">');
document.write('            <h3>Top Products</h3>');
document.write('            <a href="#">Managed Website</a>');
document.write('            <a href="#">Manage Reputation</a>');
document.write('            <a href="#">Power Tools</a>');
document.write('            <a href="#">Marketing Service</a>');
document.write('        </section>');
document.write('        <section class="flex-content padding_1x">');
document.write('            <h3>Quick Links</h3>');
document.write('            <a href="#">Jobs</a>');
document.write('            <a href="#">Brand Assets</a>');
document.write('            <a href="#">Investor Relations</a>');
document.write('            <a href="#">Terms of Service</a>');
document.write('        </section>');
document.write('        <section class="flex-content padding_1x">');
document.write('            <h3>Features</h3>');
document.write('            <a href="#">Jobs</a>');
document.write('            <a href="#">Brand Assets</a>');
document.write('            <a href="#">Investor Relations</a>');
document.write('            <a href="#">Terms of Service</a>');
document.write('        </section>');
document.write('        <section class="flex-content padding_1x">');
document.write('            <h3>Resources</h3>');
document.write('            <a href="#">Guides</a>');
document.write('            <a href="#">Research</a>');
document.write('            <a href="#">Experts</a>');
document.write('            <a href="#">Agencies</a>');
document.write('        </section>');
document.write('    </div>');
document.write('    <div class="flex">');
document.write('        <section class="flex-content padding_1x">');
document.write('            <p>Copyright ©2023 All rights reserved || website name</p>');
document.write('        </section>');
document.write('        <section class="flex-content padding_1x">');
document.write('            <a href="#"><i class="fa fa-facebook"></i></a>');
document.write('            <a href="#"><i class="fa fa-twitter"></i></a>');
document.write('            <a href="#"><i class="fa fa-dribbble"></i></a>');
document.write('            <a href="#"><i class="fa fa-linkedin"></i></a>');
document.write('        </section>');
document.write('    </div>');
document.write('</footer>');