document.write('<header class="header" id="header">');
document.write('    <nav class="navbar navbar-light fixed-top">');
document.write('        <div class="container">');
document.write('            <a href="./index.html" class="navbar-brand">');
document.write('                <img src="./frontend/img/nclogo.png" class="obj_fit_contain"  alt="">');
document.write('            </a>');
document.write('            <div class="header_links">');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="#">');
document.write('                        EmployerZone');
document.write('                    </a>');
document.write('                </li>');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="./professtionals.html">');
document.write('                        Professionals');
document.write('                    </a>');
document.write('                </li>');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="#">');
document.write('                        Resources');
document.write('                    </a>');
document.write('                </li>');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="#">');
document.write('                        About');
document.write('                    </a>');
document.write('                </li>');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="#">');
document.write('                        Corporate Careers');
document.write('                    </a>');
document.write('                </li>');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="#">');
document.write('                        Contact');
document.write('                    </a>');
document.write('                </li>');
document.write('                <li class="link_item">');
document.write('                    <a class="nav-link" href="#">');
document.write('                        Resources');
document.write('                    </a>');
document.write('                </li>');
document.write('            </div>');
document.write('            <div class="d-flex gap-2 align-items-center">');
document.write('                <li><a href="./sign-up.html" class="theme_btn text-white">Sign Up</a></li>');
document.write('                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"');
document.write('                    data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">');
document.write('                    <span class="navbar-toggler-icon"></span>');
document.write('                </button>');
document.write('            </div>');
document.write('            <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"');
document.write('                aria-labelledby="offcanvasDarkNavbarLabel">');
document.write('                <div class="offcanvas-header">');
document.write('                    <h5 style="width:100px;" class="offcanvas-title" id="offcanvasDarkNavbarLabel"><img src="./frontend/img/nclogo.png" class="obj_fit_contain" alt=""></h5>');
document.write('                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"');
document.write('                        aria-label="Close"></button>');
document.write('                </div>');
document.write('                <div class="offcanvas-body">');
document.write('                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link active" aria-current="page" href="#">');
document.write('                                Facilities');
document.write('                            </a>');
document.write('                        </li>');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link" href="#">');
document.write('                                Professionals');
document.write('                            </a>');
document.write('                        </li>');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link" href="#">');
document.write('                                Resources');
document.write('                            </a>');
document.write('                        </li>');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link" href="#">');
document.write('                                About');
document.write('                            </a>');
document.write('                        </li>');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link" href="#">');
document.write('                                Corporate Careers');
document.write('                            </a>');
document.write('                        </li>');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link" href="#">');
document.write('                                Contact');
document.write('                            </a>');
document.write('                        </li>');
document.write('                        <li class="link_item">');
document.write('                            <a class="nav-link" href="#">');
document.write('                                Resources');
document.write('                            </a>');
document.write('                        </li>');
document.write('                    </ul>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </nav>');
document.write('</header>');


